In [3]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
data = {"name": ["Ana", "Ben", "Cara"], "sales": [120, 90, 150]}
df = pd.DataFrame(data)
df

   name  sales
0   Ana    120
1   Ben     90
2  Cara    150

In [2]:

df["tax"] = df["sales"] * 0.1
high_sales = df[df["sales"] >= 100]
df = df.sort_values("sales", ascending=False)
df

   name  sales   tax
2  Cara    150  15.0
0   Ana    120  12.0
1   Ben     90   9.0

In [3]:
df.to_csv("sales_report.csv", index=False)